### PR TITLE
feat(spark): Support local filesystem in spark library for graphar-info temporarily

### LINKED ISSUE #554: feat(spark): Support local filesystem without sparksession
### Describe the enhancement requested

Curently, the scala library needs a spark process to use. But it will be a bit complicated if we only deal with local files.

I hope that we can support the local filesystem without sparksession. Now my idea is to allow the loader and some funcs in the scala library to allow the spark parameter to be None. 

```scala
def loadGraphInfo(
      graphInfoPath: String,
      spark: Option[SparkSession] = None
  )
 ```

### Component(s)

Spark

### PR DESCRIPTION
**Pull request by jasinliu**
### Reason for this PR

fix #554 

### What changes are included in this PR?

as title.

### CODE REVIEW

**Comment by jasinliu** [comment]
This PR brings a very big change in the usage. When using `spark` parameter in `info`, users must add `Some` to support this `Option`.

**Comment by jasinliu** [comment]
> This PR brings a very big change in the usage. When using `spark` parameter in `info`, users must add `Some` to support this `Option`.

I want to know how to avoid changing the user mode?

**Comment by jasinliu** [comment]
> This PR brings a very big change in the usage. When using `spark` parameter in `info`, users must add `Some` to support this `Option`.

Before the `info` module arrives, if this PR makes sense, I can try to modify and add some tests.

**Review by SemyonSinchenko — CHANGES_REQUESTED** [review]
GraphAr PySpark is broken by these changes.

**Pull request closed without merging**
