### PR TITLE
feat(c++): support static graphar

### LINKED ISSUE #538: [Feat][C++] Support static installation of arrow and graphar
### Describe the enhancement requested

Currently, GraphAr C++ supports dynamic installation, but not static installation. Arrow entry is also a dynamic method. 

Two cmake options can be added to support static installation, giving users better choices.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by jasinliu**
### Reason for this PR

fix #538

### CODE REVIEW

**Review by acezen — COMMENTED** [review]
Overall LGTM, thanks for the pull request.
The CI failed indicated that the "arrow_static" seems to make the `protobuf::libprotobuf` dependency interface **public**, it means that if we `USE_ARROW_STATIC`, we need to find and link protobuf too.

**Comment by jasinliu** [comment]
> Overall LGTM, thanks for the pull request. The CI failed indicated that the "arrow_static" seems to make the `protobuf::libprotobuf` dependency interface **public**, it means that if we `USE_ARROW_STATIC`, we need to find and link protobuf too.

Do we need to install protobuf in ci environment？

**Comment by jasinliu** [comment]
> > Overall LGTM, thanks for the pull request. The CI failed indicated that the "arrow_static" seems to make the `protobuf::libprotobuf` dependency interface **public**, it means that if we `USE_ARROW_STATIC`, we need to find and link protobuf too.
> 
> Do we need to install protobuf in ci environment？

The error in ci does not appear in dev-container.

**Comment by acezen** [comment]
> > > Overall LGTM, thanks for the pull request. The CI failed indicated that the "arrow_static" seems to make the `protobuf::libprotobuf` dependency interface **public**, it means that if we `USE_ARROW_STATIC`, we need to find and link protobuf too.
> > 
> > 
> > Do we need to install protobuf in ci environment？
> 
> The error in ci does not appear in dev-container.

The difference between `CI` and `dev-container` is that `dev-container`'arrow is latest version, but CI install `14.0.1`:
https://github.com/apache/incubator-graphar/blob/98f3850c800bf1eb47fe31cf37ecd94c6fa20487/.github/workflows/ci.yml#L59-L62

Could you try revise the CI and install the latest version too(mean not specify the version)?

**Review by acezen — APPROVED** [review]
LGTM

**Pull request merged**
