### PR TITLE
[Infra] Remove the third party action from CI

### PR DESCRIPTION
**Pull request by acezen**
## Proposed changes
Apache project only allows to use github or apache's actions, try to replace the third-party action in CI.

### CODE REVIEW

**Comment by SemyonSinchenko** [comment]
@acezen, do you need help here with all this python stuff?

**Comment by acezen** [comment]
> @acezen, do you need help here with all this python stuff?

yeah, Apache only allows project to use github/apache's actions in CI, can you help me how to replace the poetry related action in CI?

**Comment by SemyonSinchenko** [comment]
Of course. I will do it in the evening.

**Comment by acezen** [comment]
> Of course. I will do it in the evening. 

that's great! thanks Sem.

**Comment by SemyonSinchenko** [comment]
@acezen [This way](https://github.com/apache/incubator-graphar/compare/main...SemyonSinchenko:GraphAr:main#diff-1fa2e68a05cfff999e6506043eb183b3e5485b3aef83aa43dad5b1c808b01245R57) is working for me:

```yaml
    - name: Install Poetry
      run: |
          yes | sudo python3 -m pip install poetry --quiet
          cd pyspark
          poetry env use python3
```

I tried it in my fork and it [works](https://github.com/SemyonSinchenko/GraphAr/actions/runs/8569444022/job/23485349252)

I see that you already made a lot of changes, so we can merge your current work and I will fix broken pipelines, or you can just copy-paste the way how I install poetry and it should work.

**Comment by acezen** [comment]
> @acezen [This way](https://github.com/apache/incubator-graphar/compare/main...SemyonSinchenko:GraphAr:main#diff-1fa2e68a05cfff999e6506043eb183b3e5485b3aef83aa43dad5b1c808b01245R57) is working for me:
> 
> ```yaml
>     - name: Install Poetry
>       run: |
>           yes | sudo python3 -m pip install poetry --quiet
>           cd pyspark
>           poetry env use python3
> ```
> 
> I tried it in my fork and it [works](https://github.com/SemyonSinchenko/GraphAr/actions/runs/8569444022/job/23485349252)
> 
> I see that you already made a lot of changes, so we can merge your current work and I will fix broken pipelines, or you can just copy-paste the way how I install poetry and it should work.

Thanks Sem, I will try to copy-paste to check the CI.

**Comment by acezen** [comment]
Hi, @SemyonSinchenko, it works! Can you take a review for the changes?

**Comment by SemyonSinchenko** [comment]
I think we still need to switch to latest Ubuntu, because 20.04 [will stop](https://ubuntu.com/about/release-cycle) getting security updates in the middle of 2024. I would suggest latest or 22.04.

**Review by SemyonSinchenko — APPROVED** [review]
LGTM

**Comment by acezen** [comment]
> for

It seems that the CI still run a ubuntu-20.04, we can merge this change first, and change to ubuntu-latest in another PR.

**Pull request merged**
