### PR TITLE
chore: Add CHANGELOG.md

### PR DESCRIPTION
**Pull request by acezen**
### Reason for this PR

Add CHANGELOG.md to project to to document all changes made to the project.

### What changes are included in this PR?

- Add CHANGELOG.md
- add changes of v0.1.0 to v0.11.4 to CHANGELOG.md

### CODE REVIEW

**Comment by SemyonSinchenko** [comment]
Are you sure that we need to do it manually? Because google's `release-please` [action](https://github.com/googleapis/release-please-action?tab=readme-ov-file#how-release-please-works) can automate it. And this action is distributed under Apache 2.0

**Comment by acezen** [comment]
> Are you sure that we need to do it manually? Because google's `release-please` [action](https://github.com/googleapis/release-please-action?tab=readme-ov-file#how-release-please-works) can automate it. And this action is distributed under Apache 2.0

The action seems great, I think we can automate it in our future release.

**Comment by SemyonSinchenko** [comment]
> The action seems great, I think we can automate it in our future releases.

I mean should we check the format of generated CHANGELOG.md by this action and try to align the current changes to the same format?

**Comment by SemyonSinchenko** [comment]
I see. Thanks for the explanation @acezen 
LGTM, approved

**Review by SemyonSinchenko — APPROVED** [review]

**Pull request merged**
