### PR TITLE
feat(devinfra): Add test coverage to CI to measure the covering code of unit test and add banner to README (C++)

### PR DESCRIPTION
**Pull request by Elssky**
### Reason for this PR

solution to https://github.com/apache/incubator-graphar/issues/189

### What changes are included in this PR?

Add test coverage to CI to measure the covering code of unitest and add banner to README 
### Are these changes tested?

yes
### Are there any user-facing changes?

only README

### CODE REVIEW

**Comment by acezen** [comment]
Hi, @Elssky , Thanks for the contribution. I have asked Apache infrastructure team to add GraphAr to codecov[1]. When the jira ticket is addressed, it is ok to merge this change into main.

[1] https://issues.apache.org/jira/projects/INFRA/issues/INFRA-26024

**Comment by yecol** [comment]
Good PR! I have a comment, 
It seems the coverage report only covers cpp code, it would be better if it also contains java/spark code. 
(Surely it can be addressed by another issue/PR)

ref: https://about.codecov.io/language/java/

**Comment by Elssky** [comment]
> Good PR! I have a comment, It seems the coverage report only covers cpp code, it would be better if it also contains java/spark code. (Surely it can be addressed by another issue/PR)
> 
> ref: https://about.codecov.io/language/java/

yes, I will try to get java/spark code coverage info👌

**Review by acezen — APPROVED** [review]
LGTM, merged and wait the jira ticket be addressed

**Pull request merged**
