### PR TITLE
feat(java): Put java and spark libraries within a directory `maven-projects` to help easily manage and extend the multi-module maven projects

### PR DESCRIPTION
**Pull request by acezen**
### Reason for this PR

Since we would split the java library to multi-module project and spark rely on one of the modules 'info', it's better to put java and spark libraries within a directory. That help easily manage and extend the multi-module maven projects

### What changes are included in this PR?

- Put java and spark libraries within a directory `maven-project`
- Update the related link and document
### Are these changes tested?

yes

### Are there any user-facing changes?

No

### CODE REVIEW

**Comment by acezen** [comment]
This PR will make the `branch-feat-spark-java-info-refactoring` branch easily to merge into the main.

**Review by lixueclaire — APPROVED** [review]
LGTM

**Comment by acezen** [comment]
Hi, @Thespica @SemyonSinchenko, This change is related to Java and Spark, it's better to get some review or advice for the change.

**Review by SemyonSinchenko — APPROVED** [review]
LGTM

**Comment by acezen** [comment]
hi, @Thespica, the module name has been unify with directory name.

**Review by Thespica — APPROVED** [review]
LGTM~
Besides, #467 can be closed, right?

**Comment by acezen** [comment]
> LGTM~ Besides, #467 can be closed, right?

yes, #467 is solved by this PR.

**Pull request merged**
