### PR TITLE
feat: make apache-arrow ORC extension optional

### LINKED ISSUE #546: feat(c++): raise error at runtime if arrow does not support ORC
### Describe the enhancement requested
the follow-up issue of #545, try to raise error at runtime if arrow does not support ORC.

the ORC related code list below:

https://github.com/apache/incubator-graphar/blob/d00c3649d2fdee6ba0fbf612b473707688d60e3f/cpp/src/graphar/filesystem.cc#L20

https://github.com/apache/incubator-graphar/blob/d2e8196443bb62155fe55e47752d8e259f7c4ba7/cpp/src/graphar/filesystem.cc#L93

https://github.com/apache/incubator-graphar/blob/d00c3649d2fdee6ba0fbf612b473707688d60e3f/cpp/src/graphar/filesystem.cc#L236-L244

https://github.com/apache/incubator-graphar/blob/d00c3649d2fdee6ba0fbf612b473707688d60e3f/cpp/src/graphar/reader_util.cc#L20

https://github.com/apache/incubator-graphar/blob/d00c3649d2fdee6ba0fbf612b473707688d60e3f/cpp/test/test_arrow_chunk_writer.cc#L25

https://github.com/apache/incubator-graphar/blob/d2e8196443bb62155fe55e47752d8e259f7c4ba7/cpp/test/test_arrow_chunk_writer.cc#L115

https://github.com/apache/incubator-graphar/blob/d2e8196443bb62155fe55e47752d8e259f7c4ba7/cpp/test/test_builder.cc#L27

### Solution
Maybe add a macro definition in CMakeList to indicate `ARROW_ORC` support or not.

### Component(s)

C++

### PR DESCRIPTION
**Pull request by yecol**
### Reason for this PR

To fix #546,  following the discussion.

### What changes are included in this PR?

Using `ARROW_ORC` macro to safe guard the orc related code.

### Are these changes tested?

Yes, tests have changed correspondly and passed. 

### Are there any user-facing changes?

No.

### CODE REVIEW

**Comment by acezen** [comment]
the `/home/runner/work/incubator-graphar/incubator-graphar/cpp/src/graphar/filesystem.cc:242`
https://github.com/apache/incubator-graphar/blob/d00c3649d2fdee6ba0fbf612b473707688d60e3f/cpp/src/graphar/filesystem.cc#L236-L244

need the
``` 
#ifdef ARROW_ORC

#endif 
```
too

**Comment by yecol** [comment]
Screenshot 2024-07-29 at 14 23 05

It is a little weird since I already guard this block.

**Comment by yecol** [comment]
Screenshot 2024-07-29 at 14 25 29


It is a little weird since I already guarded this code block. Please approve the CI to check this again.

**Comment by acezen** [comment]
> 
> Screenshot 2024-07-29 at 14 25 29
> 
> 
> It is a little weird since I already guarded this code block. Please approve the CI to check this again.

I konw it. the `ARROW_ORC` is just avariable in CMakeList, it can not be used as a macro definition, you need to define a macro definition after WARNING

**Comment by yecol** [comment]
> > Screenshot 2024-07-29 at 14 25 29
> > It is a little weird since I already guarded this code block. Please approve the CI to check this again.
> 
> I konw it. the `ARROW_ORC` is just avariable in CMakeList, it can not be used as a macro definition, you need to define a macro definition after WARNING by `add_definitions(-DARROW_ORC)`

Still strange. In the same file, it goes ARROW_ORC code-path in line-240 and NOT defined ARROW_ORC code-path in line-21, in the same file. 

However, to avoid this inconsistency, I have added the definition.

**Review by acezen — APPROVED** [review]
LGTM

**Pull request merged**
