### PR TITLE
feat(c++)!: change the header folder and library name from `gar` to `graphar`

### PR DESCRIPTION
**Pull request by acezen**
### Reason for this PR

as issue #476 describe

### What changes are included in this PR?

- change the header folder to `include/graphar`
- change the generated library to `graphar`
- update the related document and code.

### Are these changes tested?

covered by existing tests.

### Are there any user-facing changes?

yes

**BREAKING CHANGE:  This change make the header include sentence from `include gar/` to include  graphar/ and link library from `gar` to `graphar`**

### CODE REVIEW

**Review by lixueclaire — APPROVED** [review]
LGTM, thanks to make this change. BTW, could you please help to update "gar" to "graphar" in the documentation as well?

**Comment by acezen** [comment]
> LGTM, thanks to make this change. BTW, could you please help to update "gar" to "graphar" in the documentation as well?

I have checked the docs and there is no `gar` need to update to `graphar`, if you know where it is, can you list to me?

**Comment by acezen** [comment]
> LGTM, thanks to make this change. BTW, could you please help to update "gar" to "graphar" in the documentation as well?

The document has been updated (`GAR` update to `GraphAr`), can you review again?

**Comment by lixueclaire** [comment]
> > LGTM, thanks to make this change. BTW, could you please help to update "gar" to "graphar" in the documentation as well?
> 
> The document has been updated (`GAR` update to `GraphAr`), can you review again?

Thanks for updating that. It looks that this PR can be merged now.

**Pull request merged**
